### ISSUE TITLE
Problem running distem-bootstrap on Debian 9

### ISSUE THREAD

**Issue by ksonbol** [madynes/distem#31]
Hello,

I am following the [getting started tutorial](http://distem.gforge.inria.fr/tuto_getting_started.html) to use Distem with Grid'5000 and I got stuck at the distem-bootstrap stage. 
I ran these commands to use three physical nodes:
```
frontend> oarsub -t deploy -l slash_22=1+nodes=3,walltime=5:00 -I
frontend> g5k-subnets -sp
frontend> kadeploy3 -f $OAR_NODE_FILE -e debian9-x64-nfs -k
frontend> distem-bootstrap --debian-version stretch
```
The last line gives the following error:

> [0] Auto selecting ssh key '/home/ksonbol/.ssh/id_rsa'
> [0] Copying SSH key pair files
> Warning: Permanently added 'graphite-1.nancy.grid5000.fr,172.16.68.1' (ECDSA) to the list of known hosts.
> [1] Establishing SSH connections to all nodes
> [2] Updating debian packages list
> [4] Installing debian distem packages
> [33] Installing debian misc packages
> [35] Starting coordinator daemon on graphite-1.nancy.grid5000.fr
> [38] Initializing node graphite-1.nancy.grid5000.fr
> ### Error: exec of 'distem --coordinator host=graphite-1.nancy.grid5000.fr --init-pnode graphite-1.nancy.grid5000.fr' on graphite-1.nancy.grid5000.fr failed with return status 1 ###
> ---stdout dump---
> ---stderr dump---
> /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:752:in `check_error': HTTP Status: 500, (Distem::Lib::ClientError)
> Description: "",
> Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
> <HTML>
>   <HEAD><TITLE>Internal Server Error</TITLE></HEAD>
>   <BODY>
>     <H1>Internal Server Error</H1>
>     Could not parse PKey: no start line
>     <HR>
>     <ADDRESS>
>      WEBrick/1.3.1 (Ruby/2.3.3/2016-11-21) at
>      graphite-1.nancy.grid5000.fr:4567
>     </ADDRESS>
>   </BODY>
> </HTML>
> 
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:808:in `block (2 levels) in raw_request'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:493:in `process_result'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:421:in `block in transmit'
> 	from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:413:in `transmit'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:176:in `execute'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:41:in `execute'
> 	from /usr/lib/ruby/vendor_ruby/restclient/resource.rb:67:in `post'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:807:in `block in raw_request'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:772:in `block in check_net'
> 	from /usr/lib/ruby/vendor_ruby/distem/distemlib/semaphore.rb:45:in `synchronize'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:770:in `check_net'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:806:in `raw_request'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:818:in `post_json'
> from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:52:in `pnode_init'
> 	from /usr/bin/distem:336:in `block in <main>'
> 	from /usr/bin/distem:333:in `each'
> 	from /usr/bin/distem:333:in `<main>'
> ---
> 
>

**Comment by alxmerlin** [comment]
I'm having a hard time to reproduce the problem. My first guess is that the `oarsub` command is malformed and you are only reserving one machine.
Distem then failed when trying to put the coordinator and a pnode in the same machine. 
Could you send the output of `oarstat -f -j [JOBID]` to check the reserved machines ?

**Comment by ksonbol** [comment]
Thanks for your reply, Alexandre. That is not the problem I believe. I made another reservation running the same commands mentioned above, and got the same error again. Below is the requested output:

> Job_Id: 2188855
>     job_array_id = 2188855
>     job_array_index = 1
>     name = 
>     project = default
>     owner = ksonbol
>     state = Running
>     wanted_resources = -l "{type = 'subnet'}/slash_22=1+{(type = 'default') AND production = 'NO'}/host=3,walltime=9:0:0" 
>     types = deploy
>     dependencies = 
>     assigned_resources = 2918+3368+3369+3370+3371+3372+3373+3374+3375+3376+3377+3378+3379+3380+3381+3382+3383+11911+11912+11913+11914+11915+11916+11917+11918+11919+11920+11921+11922+11923+11924+11925+11926+11927+11928+11965+11966+11967+11968+11969+11970+11971+11972+11973+11974+11975+11976+11977+11978+11979+11980+11981+11982
>     assigned_hostnames = graphite-3.nancy.grid5000.fr+gros-115.nancy.grid5000.fr+gros-118.nancy.grid5000.fr
>     queue = default
>     command = 
>     launchingDirectory = /home/ksonbol
>     stdout_file = OAR.2188855.stdout
>     stderr_file = OAR.2188855.stderr
>     jobType = INTERACTIVE
>     properties = (deploy = 'YES') AND maintenance = 'NO'
>     reservation = None
>     walltime = 9:0:0
>     submissionTime = 2019-12-11 13:23:04
>     startTime = 2019-12-11 13:24:18
>     cpuset_name = ksonbol_2188855
>     initial_request = oarsub -t deploy -l slash_22=1+nodes=3,walltime=9:00 -I
>     message = FIFO scheduling OK
>     scheduledStart = 2019-12-11 13:24:18
>     resubmit_job_id = 0
>     events =

**Comment by alxmerlin** [comment]
Ok. Can you start the distem-boostrap command on verbose mode: `distem-bootstrap --debian-version stretch --verbose` and post the output

**Comment by ksonbol** [comment]
> [0] Auto selecting ssh key '/home/ksonbol/.ssh/id_rsa'
> [0] Copying SSH key pair files
> [1] Establishing SSH connections to all nodes
> [1] Updating debian packages list
> [3] Installing debian distem packages
> [3] Installing debian misc packages
> [4] Killing previous run of distem on root@graphite-3.nancy.grid5000.fr
> [4] Starting coordinator daemon on graphite-3.nancy.grid5000.fr
> [6] Initializing node graphite-3.nancy.grid5000.fr
> ### Error: exec of 'distem --coordinator host=graphite-3.nancy.grid5000.fr --init-pnode graphite-3.nancy.grid5000.fr' on graphite-3.nancy.grid5000.fr failed with return status 1 ###
> ---stdout dump---
> ---stderr dump---
> /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:752:in `check_error': HTTP Status: 500, (Distem::Lib::ClientError)
> Description: "",
> Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
> <HTML>
>   <HEAD><TITLE>Internal Server Error</TITLE></HEAD>
>   <BODY>
>     <H1>Internal Server Error</H1>
>     Could not parse PKey: no start line
>     <HR>
>     <ADDRESS>
>      WEBrick/1.3.1 (Ruby/2.3.3/2016-11-21) at
>      graphite-3.nancy.grid5000.fr:4567
>     </ADDRESS>
>   </BODY>
> </HTML>
> 
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:808:in `block (2 levels) in raw_request'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:493:in `process_result'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:421:in `block in transmit'
> 	from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:413:in `transmit'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:176:in `execute'
> 	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:41:in `execute'
> 	from /usr/lib/ruby/vendor_ruby/restclient/resource.rb:67:in `post'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:807:in `block in raw_request'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:772:in `block in check_net'
> 	from /usr/lib/ruby/vendor_ruby/distem/distemlib/semaphore.rb:45:in `synchronize'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:770:in `check_net'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:806:in `raw_request'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:818:in `post_json'
> 	from /usr/lib/ruby/vendor_ruby/distem/netapi/client.rb:52:in `pnode_init'
> 	from /usr/bin/distem:336:in `block in <main>'
> 	from /usr/bin/distem:333:in `each'
> 	from /usr/bin/distem:333:in `<main>'
> ---

**Comment by alxmerlin** [comment]
Sorry, my mistake. I meant debug mode.
so `distem-bootstrap --debian-version stretch --debug`
The output will be huge so maybe redirect it to a file.

**Comment by ksonbol** [comment]
No problem, here you go: [link](https://paste.ubuntu.com/p/FZxCtdWcFk/)

**Comment by alxmerlin** [comment]
Ok so it seems it was a problem with how grid'5000 generate keys. It was using a format not supported by distem. You can follow the resolution on this bug here: https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=11237

In the meantime, I manually regenerate key for your account. So it should be working now. Can you confirm it's ok ?

**Comment by ksonbol** [comment]
Yes! thanks a lot. I haven't tried to actually use Distem yet, but the bootstrap script worked smoothly.
