### ISSUE TITLE
Distems blocks indefinitely when starting nodes

### ISSUE THREAD

**Issue by ksonbol** [madynes/distem#33]
Distem used to work fine but now blocks indefinitely when I run the command `client.vnode_start(node_name)` for any node. I did not change the code so I am not sure what the problem is. If I stop the code after it blocks, the coordinator node becomes inaccessible with ssh.

I am using a simple setup with 4 physical nodes and one virtual node for each of them (over Grid'5000 and the 'gros' cluster).

Below is the code needed to replicate the error:

```
require 'distem'
private_key = IO.readlines('/root/.ssh/id_rsa').join
public_key = IO.readlines('/root/.ssh/id_rsa.pub').join
sshkeys = {
  'private' => private_key,
  'public' => public_key
}
subnet_addr = "10.144.0.0/22" # replace with assigned subnet address
vnet = {
  'name' => 'testnet',
  'address' => subnet_addr
}
VNODE_LIST = ['node1', 'node2', 'node3', 'node4']
FSIMG="file:///home/ksonbol/distem_img/distem-fs-jessie.tar.gz"
pnodes = ['gros-1', 'gros-2', 'gros-3', 'gros-4'] # replace with assigned pnodes

Distem.client do |dis|
  dis.vnetwork_create(vnet['name'], vnet['address'])
  pnode_idx = 0
  VNODE_LIST.each_with_index do |node_name, idx|
    dis.vnode_create(node_name, { 'host' => pnodes[pnode_idx] }, sshkeys)
    dis.vfilesystem_create(node_name, { 'image' => FSIMG })
    dis.viface_create(node_name, 'if0', { 'vnetwork' => vnet['name'] })
    pnode_idx += 1
  end

  VNODE_LIST.each do |nodename|
    dis.vnode_start(nodename)  # blocks forever!
  end
end
```

**Comment by ksonbol** [comment]
I found the problem is related with the 'gros' cluster on Grid'5000. The same code works fine with 'grisou' and 'grimoire' clusters. I am guessing it is a Grid'5000 problem and not a Distem problem. So, I am closing this issue.

**Comment by alxmerlin** [comment]
Hello,
yes it's followed from the Grid'5000 side in the https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=11480
It's a problem with the mlx5_core, it's concern the gros (Nancy) and the troll (Grenoble) custer.
